"""initial migration

Revision ID: c5f711ebb6a3
Revises: 
Create Date: 2022-10-17 17:05:30.889797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f711ebb6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingredients',
    sa.Column('ingredientID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('categor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ingredientID')
    )
    op.create_table('Recipes',
    sa.Column('recipeID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=500), nullable=True),
    sa.Column('imageURL', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('prepTime', sa.String(length=20), nullable=True),
    sa.Column('cookTime', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('recipeID')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('is_Admin', sa.Boolean(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeIngredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipeID'], ['Recipes.recipeID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savedRecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('RecipeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savedRecipes')
    op.drop_table('recipeIngredients')
    op.drop_table('Users')
    op.drop_table('Recipes')
    op.drop_table('Ingredients')
    # ### end Alembic commands ###
